on:
  push:   # on a merge of a branch into main
    branches:
      - main
      #- '**'

jobs:
  release-on-push:
    if: ${{ contains(github.ref_name, 'build/')}}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: show branch name
        run: |
          echo "Branch Name: ${{ github.ref_name }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Get poetry release
        run: |
          RELEASE_VERSION=$(poetry version | cut -d ' ' -f 2)
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_TAG=v${RELEASE_VERSION}" >> $GITHUB_ENV
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_name: "Release ${{ env.RELEASE_VERSION }}"
          release_body: "Additional Release Info"
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
